basePath: /api/v1
definitions:
  handlers_home.SpeakRequestSerializer:
    properties:
      message:
        type: string
    required:
    - message
    type: object
host: localhost:3000
info:
  contact:
    email: pachara.chantawong@gmail.com
    name: Pachara Chantawong
  title: Go Nuxt Boilerplate API
  version: "1.0"
paths:
  /home/speak:
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers_home.SpeakRequestSerializer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 'Save provided message and return it prefixed with "You said: {message}"'
      tags:
      - Home
swagger: "2.0"
